### PR TITLE
Switch from Python quilt3 to quiltcore-java

### PR DESCRIPTION
**Pull request by dimaryaz**

### CODE REVIEW

**Comment by drernie** [comment]
Interesting. I only get four errors:
```
QuiltProductTest > should create from session FAILED
    java.lang.IllegalArgumentException at QuiltProductTest.groovy:43

QuiltProductTest > shouldSkip is true if key=SKIP FAILED
    java.lang.IllegalArgumentException at QuiltProductTest.groovy:43

QuiltProductTest > does not create README if readme=SKIP FAILED
    java.lang.IllegalArgumentException at QuiltProductTest.groovy:43

QuiltProductTest > always creates README if readme!=SKIP FAILED
    java.lang.IllegalArgumentException at QuiltProductTest.groovy:43
```

**Comment by drernie** [comment]
Eerily similar to your comment about invalid hashes:
```
java.lang.IllegalArgumentException: Invalid hash prefix: ab
	at com.quiltdata.quiltcore.Namespace.resolveHash(Namespace.java:60)
	at com.quiltdata.quiltcore.Namespace.getManifest(Namespace.java:65)
	at nextflow.quilt.jep.QuiltPackage.install(QuiltPackage.groovy:201)
	at nextflow.quilt.jep.QuiltPackage.forParsed(QuiltPackage.groovy:97)
	at nextflow.quilt.nio.QuiltPath.pkg(QuiltPath.groovy:67)
	at nextflow.quilt.QuiltProduct.<init>(QuiltProduct.groovy:122)
	at nextflow.quilt.nio.QuiltProductTest.makeProduct(QuiltProductTest.groovy:43)
	at nextflow.quilt.nio.QuiltProductTest.should create from session(QuiltProductTest.groovy:68)
```
Apparently it is not fond of the fake package name I used for testing:
```
21:52:43.641 [Test worker] DEBUG n.quilt.nio.QuiltFileSystemProvider – QuiltFileSystemProvider.getPath`[quilt+s3://bkt?key=val&key2=val2#package=pre/suf@ab&path=p/t&property=prop&workflow=wf&catalog=quiltdata.com]
21:52:43.661 [Test worker] DEBUG nextflow.quilt.jep.QuiltPackage – QuiltPackage.bkt_pre_suf: attempting install for.pkgKey bkt?key=val&key2=val2#package=pre%2fsuf@ab (okay if fails)
21:52:43.661 [Test worker] INFO  nextflow.quilt.jep.QuiltPackage – installing pre/suf from bkt...
21:52:43.668 [Test worker] INFO  nextflow.quilt.jep.QuiltPackage – hash: ab -> ab
```

**Comment by drernie** [comment]
When I fixed the hash, I could run all the unit tests and `make pkg-test`.
Are you able to run them on your local machine?

Also, do you know how to get the CI to download the test results? I can't figure out why it is erroring.

**Comment by drernie** [comment]
Silly question, but why did you open a new PR instead of using:

https://github.com/quiltdata/nf-quilt/pull/128

I remember making some of these changes there.

UPDATE: Never mind:
> But, it looks like main and quiltcore-java-demo/quiltcore-java-preview have really diverged

**Comment by dimaryaz** [comment]
Yep, tests work for me!

As for CI: it doesn't have AWS credentials, right? I get the same errors locally if I run them without credentials.

**Comment by drernie** [comment]
Ah, that was it. I also fixed the credentials in the GitHub Actions. Adding those seems to have fixed everything ~(tweaking some minor errors now).~

**Pull request merged**
